const headers = {
  ASDA1: {
    description: "[Description Of All Retail Goods]",
    nature_of_products: "[Nature Of Product]",
    type_of_treatment: "[Treatment Type]",
    number_of_packages: "[Number of Packages]",
    total_net_weight_kg: "[Net Weight]",
  },
  ASDA2: {
    description: "[Description Of All Retail Go",
    nature_of_products: "[Nature Of Product]",
    type_of_treatment: "[Treatment Ty",
    number_of_packages: "Cases",
    total_net_weight_kg: "NET Weight",
  },
  BUFFALOAD1: {
    description: "Description of goods",
    type_of_treatment: "Treatment Type (Chilled /Ambient)",
    number_of_packages: "No. of pkgs",
    total_net_weight_kg: "Item Net Weight (kgs)",
    commodity_code: "Commodity code",
  },
  CDS1: {
    description: "Product",
    type_of_treatment: "Treatment",
    number_of_packages: "# Packages",
    total_net_weight_kg: "NetWeight",
    nature_of_products: "NatureOfProduct",
  },
  COOP1: {
    description: "Product/ Part Number description",
    commodity_code: "Tariff Code EU",
    number_of_packages: "Packages",
    total_net_weight_kg: "NW total",
  },
  DAVENPORT1: {
    description: "Description of Goods",
    commodity_code: "Commodity Code",
    number_of_packages: "No. of Pkgs",
    total_net_weight_kg: "Total Net Weight",
  },
  GIOVANNI1: {
    description: "DESCRIPTION",
    commodity_code: "Commodity Code",
    number_of_packages: "Quantity",
    total_net_weight_kg: "Net Weight (KG)",
  },
  KEPAK1: {
    description: "DESCRIPTION",
    commodity_code: "Commodity Code",
    number_of_packages: "Quantity",
    total_net_weight_kg: "Net Weight (KG)",
  },
  NISA1: {
    description: "PART_NUMBER_DESCRIPTION",
    commodity_code: "TARIFF_CODE_EU",
    number_of_packages: "PACKAGES",
    total_net_weight_kg: "NET_WEIGHT_TOTAL",
    nature_of_products: "PRODUCT_TYPE_CATEGORY",
  },
  NISA2: {
    description: "PART_NUMBER_DESCRIPTION",
    commodity_code: "TARIFF_CODE_EU",
    number_of_packages: "PACKAGES",
    total_net_weight_kg: "NET_WEIGHT_TOTAL",
    nature_of_products: "PRODUCT_TYPE_CATEGORY",
  },
  NISA3: {
    description: "PART NUMBER DESCRIPTION",
    commodity_code: "TARIFF CODE EU",
    number_of_packages: "PACKAGES",
    total_net_weight_kg: "NET WEIGHT TOTAL",
    nature_of_products: "PRODUCT TYPE CATEGORY",
  },
  NUTRICIA1: {
    description: "DESCRIPTION",
    commodity_code: "Commodity Code",
    number_of_packages: "Quantity",
    total_net_weight_kg: "Net Weight (KG)",
  },
  SAINSBURYS1: {
    description: "Product / Part Number Description",
    commodity_code: "Commodity Code",
    number_of_packages: "Packages",
    total_net_weight_kg: "Net\nWeight / Package KG",
    nature_of_products: "Product Type / Category",
    type_of_treatment: "Packaging Type",
  },
  TESCO1: {
    description: "Product/ Part Number description",
    commodity_code: "Tariff Code UK",
    number_of_packages: "Packages",
    total_net_weight_kg: "Net Weight",
    type_of_treatment: "Treatment Type",
  },
  TESCO2: {
    description: "Description of goods",
    commodity_code: "Commodity code",
    number_of_packages: "No. of pkgs",
    total_net_weight_kg: "Total Net Weight",
  },
  TESCO3: {
    description: "Product/ Part Number description",
    commodity_code: "Tariff Code UK",
    number_of_packages: "Packages",
    total_net_weight_kg: "Net Weight",
    type_of_treatment: "Treatment Type",
  },
};

module.exports = headers;
