const ParserModel = {
  NOMATCH: "no-match",
  NOREMOS: "no-remos",
  TJMORRIS1: "tjmorris-1",
  TJMORRIS2: "tjmorris-2",
  ASDA1: "asda-1",
  ASDA2: "asda-2",
  ASDA3: "asda-3",
  SAINSBURYS1: "sainsburys-1",
  BANDM1: "bandm-1",
  TESCO1: "tesco-1",
  TESCO2: "tesco-2",
  TESCO3: "tesco-3",
  FOWLERWELCH1: "fowlerwelch-1",
  MARS1: "mars-1",
  NISA1: "nisa-1",
  NISA2: "nisa-2",
  BUFFALOAD1: "buffaload-1",
  CDS1: "cds-1",
  COOP1: "coop-1",
  DAVENPORT1: "davenport-1",
  DAVENPORT2: "davenport-2",
  GIOVANNI1: "giovanni-1",
  GIOVANNI2: "giovanni-2",
  KEPAK1: "kepak-1",
  NUTRICIA1: "nutricia-1",
  NUTRICIA2: "nutricia-2",
  WARRENS1: "warrens-1",
  ICELAND1: "iceland-1",
  MANDS1: "mands-1",
  BOOKER1: "booker-1",
  BOOTS1: "boots-1",
  SAVERS1: "savers-1",
  GREGGS1: "greggs-1",
  GIOVANNI3: "giovanni-3",
};

module.exports = ParserModel;
