# templates/di-migrate-template.yml

parameters:
  - name: modelIds
    type: string
  - name: sourceEndpoint
    type: string
  - name: targetEndpoint
    type: string
  - name: azureSubscription
    type: string
  - name: poolName
    type: string
  - name: environmentName
    type: string
  - name: sourceSubscriptionId
    type: string
  - name: targetSubscriptionId
    type: string

jobs:
  - deployment: copyModel
    displayName: Copy model to ${{ parameters.environmentName }}
    pool:
      name: ${{ parameters.poolName }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: UseNode@1
              inputs:
                version: "16.x"

            - script: |
                npm install
              displayName: "Install npm dependencies"

            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: "bash"
                scriptLocation: "inlineScript"
                inlineScript: |
                  az account set --subscription ${{ parameters.sourceSubscriptionId }}
                  export NODE_OPTIONS=--tls-min-v1.2
                  openssl s_client -connect sndadpinfdi4401.cognitiveservices.azure.com:443 -tls1_2
                  nc -v -w 3 sndadpinfdi4401.cognitiveservices.azure.com 443
                  nslookup sndadpinfdi4401.cognitiveservices.azure.com
                  curl -v https://sndadpinfdi4401.cognitiveservices.azure.com
                  node $(Build.SourcesDirectory)/.azuredevops/scripts/diMigrate.js
              env:
                MODEL_IDS: ${{ parameters.modelIds }}
                SOURCE_ENDPOINT: ${{ parameters.sourceEndpoint }}
                TARGET_ENDPOINT: ${{ parameters.targetEndpoint }}
