const ParserModel = require("../../../../../../app/services/parser-model");

module.exports = {
  validModel: {
    Customer_Order: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: "RMS-GB-000323-001" },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        C: "Commodity Code",
        F: "Description of Goods",
        H: "No. of Pkgs(180)",
        K: "Total Net Weight(X)",
      },

      {
        C: "709200010",
        F: "ASPARAGUS BUNDLE",
        H: 160,
        K: 40.0,
      },
      {
        C: "709599000",
        F: "OYSTER MUSHROOM",
        H: 20,
        K: 30.0,
      },
    ],
  },
  invalidModel_IncorrectEstablishmentNumber: {
    PackingList_Extract: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: "INCORRECT" },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        C: "Commodity Code",
        F: "Description of Goods",
        H: "No. of Pkgs(X)",
        K: "Total Net Weight(X)",
      },
    ],
  },
  invalidModel_MissingHeaders: {
    PackingList_Extract: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: "RMS-GB-000323-001" },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  invalidModel_IncorrectHeaders: {
    PackingList_Extract: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: "RMS-GB-000323-001" },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        A: "NOT",
        B: "CORRECT",
        C: "HEADER",
      },
    ],
  },
  invalidModel_MissingColumnCells: {
    Customer_Order: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: "RMS-GB-000323-001" },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        C: "Commodity Code",
        F: "Description of Goods",
        H: "No. of Pkgs(180)",
        K: "Total Net Weight(X)",
      },

      {
        C: null,
        F: "ASPARAGUS BUNDLE",
        H: 160,
        K: 40.0,
      },
      {
        C: "709599000",
        F: "OYSTER MUSHROOM",
        H: 20,
        K: null,
      },
    ],
  },
  emptyModel: {
    PackingList_Extract: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { C: null },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {
        C: null,
      },
    ],
  },
  validTestResult: {
    business_checks: {
      all_required_fields_present: true,
    },
    items: [
      {
        commodity_code: "709200010",
        description: "ASPARAGUS BUNDLE",
        nature_of_products: null,
        number_of_packages: 160,
        total_net_weight_kg: 40.0,
        type_of_treatment: null,
      },
      {
        commodity_code: "709599000",
        description: "OYSTER MUSHROOM",
        nature_of_products: null,
        number_of_packages: 20,
        total_net_weight_kg: 30.0,
        type_of_treatment: null,
      },
    ],
    registration_approval_number: "RMS-GB-000323-001",
    parserModel: ParserModel.DAVENPORT1,
  },
  invalidTestResult_MissingCells: {
    business_checks: {
      all_required_fields_present: false,
    },
    items: [
      {
        commodity_code: null,
        description: "ASPARAGUS BUNDLE",
        nature_of_products: null,
        number_of_packages: 160,
        total_net_weight_kg: 40.0,
        type_of_treatment: null,
      },
      {
        commodity_code: "709599000",
        description: "OYSTER MUSHROOM",
        nature_of_products: null,
        number_of_packages: 20,
        total_net_weight_kg: null,
        type_of_treatment: null,
      },
    ],
    registration_approval_number: "RMS-GB-000323-001",
    parserModel: ParserModel.DAVENPORT1,
  },
};
