trigger: none

parameters:
  - name: MODEL_IDS
    displayName: "Model IDs (comma-separated)"
    type: string
    default: "iceland1-v1" # Input format: "model1,model2,model3"

stages:
  - stage: SND_to_DEV
    displayName: "Migration from SND to DEV"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: "https://sndadpinfdi4401.cognitiveservices.azure.com/"
          sourceDIRGName: "SNDADPINFRG4401"
          sourceDIName: "SNDADPINFDI4401"
          targetEndpoint: "https://devadpinfdi1401.cognitiveservices.azure.com/"
          targetDIRGName: "DEVADPINFRG1401"
          targetDIName: "DEVADPINFDI1401"
          azureSubscription: "AZR-ADP-SND4_DEV1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV3"
          environmentName: "DEV1"
          sourceSubscriptionId: "da83801b-f7e0-4510-9848-67d87b1009e2"
          targetSubscriptionId: "19164a52-70b4-46bf-be9b-0cb3edd7c120"

  - stage: DEV_to_TST
    dependsOn: SND_to_DEV
    displayName: "Migration from DEV to TST"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: "https://devadpinfdi1401.cognitiveservices.azure.com/"
          sourceDIRGName: ""
          sourceDIName: ""
          targetEndpoint: "https://tstadpinfdi1401.cognitiveservices.azure.com/"
          targetDIRGName: ""
          targetDIName: ""
          azureSubscription: "AZR-ADP-DEV1_TST1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV3"
          environmentName: "TST1"
          sourceSubscriptionId: "19164a52-70b4-46bf-be9b-0cb3edd7c120"
          targetSubscriptionId: "e386d700-ffc5-475c-897a-3f556e66acb8"

  - stage: TST_to_PRE
    dependsOn: DEV_to_TST
    displayName: "Migration from TST to PRE"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: "https://tstadpinfdi1401.cognitiveservices.azure.com/"
          sourceDIRGName: ""
          sourceDIName: ""
          targetEndpoint: "https://preadpinfdi1401.cognitiveservices.azure.com/"
          targetDIRGName: ""
          targetDIName: ""
          azureSubscription: "AZR-ADP-TST1_PRE1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV5"
          environmentName: "PRE1"
          sourceSubscriptionId: "e386d700-ffc5-475c-897a-3f556e66acb8"
          targetSubscriptionId: "972e5314-c0a2-4423-bc39-ce43c8b5e4a6"

  - stage: PRE_to_PRD
    dependsOn: TST_to_PRE
    displayName: "Migration from PRE to PRD"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: "https://preadpinfdi1401.cognitiveservices.azure.com/"
          sourceDIRGName: ""
          sourceDIName: ""
          targetEndpoint: "https://prdadpinfdi1401.cognitiveservices.azure.com/"
          targetDIRGName: ""
          targetDIName: ""
          azureSubscription: "AZR-ADP-PRE1_PRD1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV5"
          environmentName: "PRD1"
          sourceSubscriptionId: "972e5314-c0a2-4423-bc39-ce43c8b5e4a6"
          targetSubscriptionId: "3f906099-3c40-4e1d-adc1-112ff3af128b"
