trigger: none

parameters:
  - name: MODEL_IDS
    displayName: "Model IDs (comma-separated)"
    type: string
    default: "" # Input format: "model1,model2,model3"

stages:
  - stage: SND_to_DEV
    displayName: "Migration from SND to DEV"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: $(SND_ENDPOINT)
          sourceDIRGName: "SNDADPINFRG4401"
          sourceDIName: "SNDADPINFDI4401"
          targetEndpoint: $(DEV_ENDPOINT)
          targetDIRGName: "DEVADPINFRG1401"
          targetDIName: "DEVADPINFDI1401"
          azureSubscription: "AZR-ADP-SND4_DEV1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV3"
          environmentName: "DEV1"
          sourceSubscriptionId: $(SND_SUBSCRIPTION_ID)
          targetSubscriptionId: $(DEV_SUBSCRIPTION_ID)

  - stage: DEV_to_TST
    dependsOn: SND_to_DEV
    displayName: "Migration from DEV to TST"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: $(DEV_ENDPOINT)
          sourceDIRGName: "DEVADPINFRG1401"
          sourceDIName: "DEVADPINFDI1401"
          targetEndpoint: $(TST_ENDPOINT)
          targetDIRGName: "TSTADPINFRG1401"
          targetDIName: "TSTADPINFDI1401"
          azureSubscription: "AZR-ADP-DEV1_TST1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV3"
          environmentName: "TST1"
          sourceSubscriptionId: $(DEV_SUBSCRIPTION_ID)
          targetSubscriptionId: $(TST_SUBSCRIPTION_ID)
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - stage: TST_to_PRE
    dependsOn: DEV_to_TST
    displayName: "Migration from TST to PRE"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: $(TST_ENDPOINT)
          sourceDIRGName: "TSTADPINFRG1401"
          sourceDIName: "TSTADPINFDI1401"
          targetEndpoint: $(PRE_ENDPOINT)
          targetDIRGName: "PREADPINFRG1401"
          targetDIName: "PREADPINFDI1401"
          azureSubscription: "AZR-ADP-TST1_PRE1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV5"
          environmentName: "PRE1"
          sourceSubscriptionId: $(TST_SUBSCRIPTION_ID)
          targetSubscriptionId: $(PRE_SUBSCRIPTION_ID)
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  - stage: PRE_to_PRD
    dependsOn: TST_to_PRE
    displayName: "Migration from PRE to PRD"
    jobs:
      - template: ./templates/di-migrate-template.yml
        parameters:
          modelIds: ${{ parameters.MODEL_IDS }}
          sourceEndpoint: $(PRE_ENDPOINT)
          sourceDIRGName: "PREADPINFRG1401"
          sourceDIName: "PREADPINFDI1401"
          targetEndpoint: $(PRD_ENDPOINT)
          targetDIRGName: "PRDADPINFRG1401"
          targetDIName: "PRDADPINFDI1401"
          azureSubscription: "AZR-ADP-PRE1_PRD1"
          poolName: "DEFRA-COMMON-ubuntu2004-SSV5"
          environmentName: "PRD1"
          sourceSubscriptionId: $(PRE_SUBSCRIPTION_ID)
          targetSubscriptionId: $(PRD_SUBSCRIPTION_ID)
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
