pr:
  branches:
    include:
      - test-network

trigger:
  branches:
    include:
      - test-network

pool:
  name: 'DEFRA-COMMON-ubuntu2004-SSV5'

jobs:
- job: NetworkConnectivityTest
  displayName: 'Network Connectivity Test'
  steps:
    - script: |
        echo "hello world"
      displayName: 'Hello World Test'
