- key: MESSAGE_QUEUE_HOST
  value: "DEVADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "devadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "devadpinfmi1401-trade-exportscore-plp"   