- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps4401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "sndadpinfmi4401-trade-exportscore-plp"
- key: STORAGE_ACCOUNT_NAME
  value: "sndadpinfst4401tradeplp"
- key: TP_QUEUE_HOST
  value: "SNDTREINFSB1001.servicebus.windows.net"
- key: TP_TENANT_ID
  value: "c9d74090-b4e6-4b04-981d-e6757a160812"
- key: FORM_RECOGNIZER_ENDPOINT
  value: "https://sndadpinfdi4401.cognitiveservices.azure.com/"
