- key: MESSAGE_QUEUE_HOST
  value: "PRDADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "prdadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "prdadpinfmi1401-trade-exportscore-plp"
- key: TP_QUEUE_HOST
  value: "PRDTREINFSB1001.servicebus.windows.net"
- key: TP_TENANT_ID
  value: "bce3d7d1-cbbd-481e-8c81-eaecfc38b551"
