- key: MESSAGE_QUEUE_HOST
  value: "TSTADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "tstadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "tstadpinfmi1401-trade-exportscore-plp"
- key: TP_QUEUE_HOST
  value: "TSTTREINFSB1001.servicebus.windows.net"
- key: TP_TENANT_ID
  value: "c9d74090-b4e6-4b04-981d-e6757a160812"
