- key: MESSAGE_QUEUE_HOST
  value: "PREADPINFSB1401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "preadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "preadpinfmi1401-trade-exportscore-plp"
- key: TP_QUEUE_HOST
  value: "PRETREINFSB1001.servicebus.windows.net"
- key: TP_TENANT_ID
  value: "9e1ba897-3a49-4461-b406-377db4ec2959"
- key: FORM_RECOGNIZER_ENDPOINT
  value: "https://preadpinfdi1401.cognitiveservices.azure.com/"
