- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_QUEUE_HOST
  value: "DEVADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "devadpdbsps3401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "devadpinfmi3401-trade-exportscore-plp"   