  type: "keyvault"
- key: MESSAGE_QUEUE_HOST
  value: "PRDADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "prdadpdbsps3401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "prdadpinfmi3401-trade-exportscore-plp"   