- key: MESSAGE_QUEUE_HOST
  value: "PREADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "preadpdbsps3401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "preadpinfmi3401-trade-exportscore-plp"   