- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB3401.servicebus.windows.net"
- key: POSTGRES_HOST
  value: "sndadpdbsps3401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "sndadpinfmi3401-trade-exportscore-plp"
- key: STORAGE_ACCOUNT_NAME
  value: "tradeplp"
