const ParserModel = require("../../../../../app/services/parser-model");

module.exports = {
  validModel: {
    "Customer Order": [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        A: "Item",
        B: "Product code",
        C: "Commodity code",
        D: "Online Check",
        E: "Meursing code",
        F: "Description of goods",
        G: "Country of Origin",
        H: "No. of pkgs \r\n(1547)",
        I: "Type of pkgs",
        J: "Total Gross Weight \r\n(11015.700kgs)",
        K: "Total Net Weight \r\n(7921.700kgs)",
        L: "Total Line Value \r\n(41662.4)",
        M: "NIIRMS Dispatch number",
        N: "Treatment Type (Chilled /Ambient)",
        O: "NIRMS Lane (R/G)",
        P: "Secondary Qty",
        Q: "Cert Type Req",
        R: "Cert Number",
      },
      {
        A: "1",
        B: "1582084",
        C: "0702000007",
        D: "Check - 0702000007",
        E: "",
        F: "Nightingale Cherry Tomatoes TS 42x250g",
        G: "Morocco",
        H: "32",
        I: "Cases",
        J: "400",
        K: "336",
        L: "712.32",
        M: "RMS-GB-000174-004",
        N: "Chilled",
        O: "G",
        P: "",
        Q: "",
        R: "",
      },
      {
        A: "2",
        B: "3153779",
        C: "0702000007",
        D: "Check - 0702000007",
        E: "",
        F: "Cherry Tomatoes TS Core 30x300G",
        G: "Morocco",
        H: "39",
        I: "Cases",
        J: "429",
        K: "351",
        L: "889.2",
        M: "RMS-GB-000174-004",
        N: "Chilled",
        O: "G",
        P: "",
        Q: "",
        R: "",
      },
    ],
  },
  invalidModel_MissingColumnCells: {
    "Customer Order": [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {
        A: "Item",
        B: "Product code",
        C: "Commodity code",
        D: "Online Check",
        E: "Meursing code",
        F: "Description of goods",
        G: "Country of Origin",
        H: "No. of pkgs \r\n(1547)",
        I: "Type of pkgs",
        J: "Total Gross Weight \r\n(11015.700kgs)",
        K: "Total Net Weight \r\n(7921.700kgs)",
        L: "Total Line Value \r\n(41662.4)",
        M: "NIIRMS Dispatch number",
        N: "Treatment Type (Chilled /Ambient)",
        O: "NIRMS Lane (R/G)",
        P: "Secondary Qty",
        Q: "Cert Type Req",
        R: "Cert Number",
      },
      {
        A: "1",
        B: "1582084",
        C: "0702000007",
        D: "Check - 0702000007",
        E: "",
        F: "Nightingale Cherry Tomatoes TS 42x250g",
        G: "Morocco",
        H: "32",
        I: "Cases",
        J: "400",
        K: null,
        L: "712.32",
        M: "RMS-GB-000174-004",
        N: "Chilled",
        O: "G",
        P: "",
        Q: "",
        R: "",
      },
      {
        A: "2",
        B: "3153779",
        C: "0702000007",
        D: "Check - 0702000007",
        E: "",
        F: "Cherry Tomatoes TS Core 30x300G",
        G: "Morocco",
        H: "39",
        I: "Cases",
        J: "429",
        K: "351",
        L: "889.2",
        M: "RMS-GB-000174-004",
        N: null,
        O: "G",
        P: "",
        Q: "",
        R: "",
      },
    ],
  },
  emptyModel: {
    "Customer Order": [
      {
        E: "Dispatch RMS Establishment",
        O: "Product/ Part Number description",
        P: "Tariff Code EU",
        Q: "Packages",
        S: "NW total",
      },
      {
        E: null,
      },
    ],
  },
  validTestResult: {
    business_checks: {
      all_required_fields_present: true,
    },
    items: [
      {
        commodity_code: "0702000007",
        description: "Nightingale Cherry Tomatoes TS 42x250g",
        nature_of_products: null,
        number_of_packages: "32",
        total_net_weight_kg: "336",
        type_of_treatment: "Chilled",
      },
      {
        commodity_code: "0702000007",
        description: "Cherry Tomatoes TS Core 30x300G",
        nature_of_products: null,
        number_of_packages: "39",
        total_net_weight_kg: "351",
        type_of_treatment: "Chilled",
      },
    ],
    registration_approval_number: "RMS-GB-000174-004",
    parserModel: ParserModel.WARRENS1,
  },
  invalidTestResult_MissingCells: {
    business_checks: {
      all_required_fields_present: false,
    },
    items: [
      {
        commodity_code: "0702000007",
        description: "Nightingale Cherry Tomatoes TS 42x250g",
        nature_of_products: null,
        number_of_packages: "32",
        total_net_weight_kg: null,
        type_of_treatment: "Chilled",
      },
      {
        commodity_code: "0702000007",
        description: "Cherry Tomatoes TS Core 30x300G",
        nature_of_products: null,
        number_of_packages: "39",
        total_net_weight_kg: "351",
        type_of_treatment: null,
      },
    ],
    registration_approval_number: "RMS-GB-000174-004",
    parserModel: ParserModel.WARRENS1,
  },
};
