const ParserModel = require("../../../../../../app/services/parser-model");

module.exports = {
  validModel: {
    Sheet1: [
      {
        A: "Consignor / Place o f Despatch",
        B: "CONSIGNEE",
        C: "Trailer",
        D: "Seal",
        E: "Store",
        F: "STORENAME",
        G: "Order",
        H: "Cage/Ref",
        I: "Group",
        J: "TREATMENTTYPE",
        K: "Sub-Group",
        L: "Description",
        M: "Item",
        N: "Description",
        O: "Tariff/Commodity",
        P: "Cases",
        Q: "Gross Weight Kg",
        R: "Net Weight Kg",
        S: "Cost",
        T: "Country of Origin",
        U: "VAT Status",
        V: "SPS",
        W: "Consignment ID",
        X: "Processed?",
        Y: "Created Timestamp",
      },
      {
        A: "RMS-GB-000010-001",
        J: "CHILLED",
        L: "LETTUCE & BAGGED SALADS",
        N: "Description",
        O: "0408192000",
        P: "2",
        R: "1.4",
      },
      {
        A: "RMS-GB-000010-001",
        J: "FRESH PRODUCTS",
        L: "LETTUCE & BAGGED SALADS",
        N: "FLORETTE SWEET & CRUNCHY 250G",
        O: "1602906100",
        P: "4",
        R: "8",
      },
    ],
  },
  invalidModel_MissingColumnCells: {
    Sheet1: [
      {
        A: "Consignor / Place o f Despatch",
        B: "CONSIGNEE",
        C: "Trailer",
        D: "Seal",
        E: "Store",
        F: "STORENAME",
        G: "Order",
        H: "Cage/Ref",
        I: "Group",
        J: "TREATMENTTYPE",
        K: "Sub-Group",
        L: "Description",
        M: "Item",
        N: "Description",
        O: "Tariff/Commodity",
        P: "Cases",
        Q: "Gross Weight Kg",
        R: "Net Weight Kg",
        S: "Cost",
        T: "Country of Origin",
        U: "VAT Status",
        V: "SPS",
        W: "Consignment ID",
        X: "Processed?",
        Y: "Created Timestamp",
      },
      {
        A: "RMS-GB-000010-001",
        J: null,
        L: "LETTUCE & BAGGED SALADS",
        N: "Description",
        O: "0408192000",
        P: "2",
        R: "1.4",
      },
      {
        A: "RMS-GB-000010-001",
        J: "FRESH PRODUCTS",
        L: "LETTUCE & BAGGED SALADS",
        N: "FLORETTE SWEET & CRUNCHY 250G",
        O: "1602906100",
        P: "4",
        R: null,
      },
    ],
  },
  emptyModel: {
    Sheet1: [
      {
        A: "Consignor / Place o f Despatch",
        J: "TREATMENTTYPE",
        L: "SANDWICHES",
        N: "28 TUNA CRUNCH TIGER ROLL",
        O: "Tariff/Commodity",
        P: "Cases",
        R: "Net Weight Kg",
      },
      {
        A: null,
      },
    ],
  },
  validTestResult: {
    business_checks: {
      all_required_fields_present: true,
    },
    items: [
      {
        commodity_code: "0408192000",
        description: "Description",
        nature_of_products: "LETTUCE & BAGGED SALADS",
        number_of_packages: "2",
        total_net_weight_kg: "1.4",
        type_of_treatment: "CHILLED",
      },
      {
        commodity_code: "1602906100",
        description: "FLORETTE SWEET & CRUNCHY 250G",
        nature_of_products: "LETTUCE & BAGGED SALADS",
        number_of_packages: "4",
        total_net_weight_kg: "8",
        type_of_treatment: "FRESH PRODUCTS",
      },
    ],
    registration_approval_number: "RMS-GB-000010-001",
    parserModel: ParserModel.TJMORRIS1,
  },
  invalidTestResult_MissingCells: {
    business_checks: {
      all_required_fields_present: false,
    },
    items: [
      {
        commodity_code: "0408192000",
        description: "Description",
        nature_of_products: "LETTUCE & BAGGED SALADS",
        number_of_packages: "2",
        total_net_weight_kg: "1.4",
        type_of_treatment: null,
      },
      {
        commodity_code: "1602906100",
        description: "FLORETTE SWEET & CRUNCHY 250G",
        nature_of_products: "LETTUCE & BAGGED SALADS",
        number_of_packages: "4",
        total_net_weight_kg: null,
        type_of_treatment: "FRESH PRODUCTS",
      },
    ],
    registration_approval_number: "RMS-GB-000010-001",
    parserModel: ParserModel.TJMORRIS1,
  },
};
